(part "EC11E18244AU"
    (packageRef "EC11E18244AU")
    (interface
        (port "A1" (symbPinId 1) (portName "A1") (portType INOUT))
        (port "B1" (symbPinId 2) (portName "B1") (portType INOUT))
        (port "C1" (symbPinId 3) (portName "C1") (portType INOUT))
        (port "D1" (symbPinId 4) (portName "COM") (portType INOUT))
        (port "E1" (symbPinId 5) (portName "NO") (portType INOUT))
        (port "MH1" (symbPinId 6) (portName "MH_1") (portType INOUT))
        (port "MH2" (symbPinId 7) (portName "MH_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "ALPS Electric")
    (property "Manufacturer_Part_Number" "EC11E18244AU")
    (property "Mouser_Part_Number" "688-EC11E18244AU")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Alps-Alpine/EC11E18244AU?qs=YMSFtX0bdJDrS4vspzwcPg%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Alps 18 Pulse Incremental Mechanical Rotary Encoder with a 6 mm Flat Shaft (Not Indexed), Through Hole 10mA 5V DC")
    (property "Datasheet_Link" "https://tech.alpsalpine.com/cms.media/product_catalog_ec_01_ec11e_en_611f078659.pdf")
    (property "symbolName1" "EC11E18244AU")
)
